[package]
name = "draftsmith_render"
version = "0.1.0"
edition = "2021"

[dependencies]
comrak = "0.29.0"
regex = "1.11.1"
rhai = "1.19.0"


[[bin]]
name = "md_converter"
path = "src/bin/md_converter.rs"

[dependencies.clap]
version = "4.5.20"
optional = true
features = ["derive"]
